# Generated by Django 4.2.16 on 2024-09-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="playlist_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
