# Generated by Django 4.2.16 on 2024-09-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_round_release_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
