# Generated by Django 4.2.16 on 2024-09-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_song_total_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="round_finished",
            field=models.BooleanField(default=False),
        ),
    ]
