# Generated by Django 4.2.16 on 2024-09-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_round_round_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="playlist_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
