# Generated by Django 4.2.16 on 2024-10-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_round_playlist_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacySong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=150)),
                ("song", models.CharField(max_length=150)),
                ("album", models.CharField(blank=True, max_length=150)),
                ("release_year", models.CharField(blank=True, max_length=4)),
                ("date_added", models.CharField(blank=True, max_length=10)),
                ("spotify_url", models.URLField(blank=True)),
                ("pgp_num", models.CharField(blank=True, max_length=10, null=True)),
                ("pgp_tema", models.CharField(blank=True, max_length=150, null=True)),
                ("pgp_arr", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "pgp_plassering",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "pgp_levert_av",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
            options={
                "db_table": "pgp",
            },
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("player", "song")},
        ),
    ]
