# Generated by Django 4.2.16 on 2024-11-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_legacysong_alter_vote_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("total_points_pgp", models.IntegerField(default=0)),
                (
                    "highest_score_song",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("highest_score", models.IntegerField(default=0)),
                (
                    "lowest_score_song",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("lowest_score", models.IntegerField(default=0)),
                ("organizer_history", models.JSONField(blank=True, default=list)),
                ("average_score", models.FloatField(default=0)),
                ("rounds_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("bottoms", models.IntegerField(default=0)),
                ("disqualifications", models.IntegerField(default=0)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="app.player",
                    ),
                ),
            ],
        ),
    ]
