# Generated by Django 4.2.16 on 2024-11-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_playerstats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerstats",
            name="average_score",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="disqualifications",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="highest_score",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="highest_score_song",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="lowest_score",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="lowest_score_song",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="organizer_history",
        ),
    ]
